User.create(username: "kyle", password_digest: "horsch", email: "kyle@aol.com")
User.create(username: "kate", password_digest: "mclean", email: "kate@aol.com")
User.create(username: "kristin", password_digest: "styler", email: "kristin@aol.com")
User.create(username: "cheryl", password_digest: "leahy", email: "cheryl@aol.com")

Beer.create(name: "Honeyspot", brewery: "Two Roads", user_id: "1")
Beer.create(name: "Lil Heaven", brewery: "Two Roads", user_id: "1")
Beer.create(name: "Rebel IPA", brewery: "Sam Adams", user_id: "3")
Beer.create(name: "BudLight", brewery: "Anheuser-Busch", user_id: "4")
Beer.create(name: "BudHeavy", brewery: "Anheuser-Busch", user_id: "4")
Beer.create(name: "PBR", brewery: "Pabst Brewing", user_id: "1")
Beer.create(name: "All Day IPA", brewery: "Founders", user_id: "1")
